### ISSUE TITLE
iOS No route action - NavigationBar

### ISSUE THREAD

**Issue by alperozisik** [smartface/router#2]
![img_f9c793cc2344-1](https://user-images.githubusercontent.com/7248325/46244344-40b07280-c3e6-11e8-9a84-f9756c7cfda3.jpeg)
As seen in the attachment, it looks like there is a navigation bar present. As far as I know, the navigation bar is visible as long as the page (view) is within a navigation controller; I might be wrong about it. Why there is a navigation controller at all?
Is it possible to make if full black without a navigation bar?

**Comment by alperozisik** [comment]
It is possible to use the blue screen as the Android does:
![screenshot_20180929-130217](https://user-images.githubusercontent.com/7248325/46244501-63438b00-c3e8-11e8-8b95-73c8d1bd8c52.png)

**Comment by cenkce** [comment]
it solved in 1.0.0-beta.1
