### ISSUE TITLE
Does passing router is required?

### ISSUE THREAD

**Issue by dondutunel** [smartface/router#24]
For now as i know handling router on a page is like below : 

```
Route.of({
            path: "/pages/page1",
            build: (router, route) => {
                let Page1 = require("pages/page1");
                var page1 = new Page1();
                page1.router = router;
                return page1;
            }
        })
```

```
//page1 
        //on super
    function(_super, pageProps = {}, router, route) {
        _super(this,pageProps);   
        this.router=router
        this.btnNext.onPress = () => this.router.push("/pages/page2")
    });
```

When router was not passed to the page it returned error that router was undefined. I'm curious about if passing router required or not.

**Comment by cenkce** [comment]
```function(_super, pageProps = {}, router, route)``` this part is constructor therefore you must pass router to constructor like that **new Page1(router)**
