### ISSUE TITLE
Modal inside of modal is not being dismissed correctly

### ISSUE THREAD

**Issue by illegalDisease** [smartface/router#25]
Affected version -> 1.1.2
Tried on 1.1.1 and lower and no issues has been experienced.

Case -> When a StackRouter ( modal ) is defined inside of another StackRouter ( modal ), navigating through the StackRouter back and forth causes the outermost StackRouter to not being dismissed ( pressing the done / back button ) and causes the app to stay on that page.

Guess -> When another StackRouter is pushed, the history somehow defines its parent StackRouter as root, therefore it can't navigate back in history. Navigating from that StackRouter to another routes ( modal or not ) works fine.

**Comment by cenkce** [comment]
please use @smartface/router@1.2.0
