### ISSUE TITLE
Closing all open modals and then switching tabs

### ISSUE THREAD

**Issue by burakgul** [smartface/router#28]
In our current application flow, after the user completes a certain transactional operation, the user can never go back to any of the previous screens and must switch to a new tab.

How can we achieve this behavior? e.g. Open 2 modals ; then close all of them without any interaction at once or without animation and then move to a new tab.

**Comment by illegalDisease** [comment]
`routeDidEnter: (router, route) => {
                        const { view, action } = route.getState();
                        if (action === "POP") {
                            setTimeout(() => {
                                router.dismiss(() => {
                                    router.push("/nav/tabs/discover/landing");
                                }, false);

                            }, 200);
                        }
                    }`

Setting a timeout like this causes the dismiss & push flows to work correctly
