### ISSUE TITLE
 New Router, push new page from NativeStackRouter. Back button problem

### ISSUE THREAD

**Issue by yenerciftci** [smartface/router#30]
i wrote app.js that it has root Router. The Root Router has one NativeStackRouter that it has 2 route , one Route(single). Firstly, i pushed "/pages/pages1" that i gived name page1('path /pages/page1'). 
	
	My Root Router Struct
	
	Root Router
		----- NativeStackRouter
		  * page1
		  * page2
		----- Route
		  * pushPage

My First navigate scenario:
When app loaded, first i pushed to "page1" that it's in NativeStackRouter- After i pushed "page2" with router. Page1 and Page2  in same StackRouter. Then push "pushPage" route outside from NativeStackRouter.

When "pushPage"  was appear, i call method router.goBack() function. 
	app return page1 in NativeStackRouter.
   
But i excepted;  stack state clear and dont allow router.goBack()
                    or return back to page2  when i call router.goBack()
   Second scenario
     page1->page2->pagePush then call router.goBack() (returning page1) -> page2 then call router.goBack();
     after this scenario -> router and state returning null;

**Comment by yenerciftci** [comment]
i have added to gist. link is below
https://gist.github.com/yenerciftci/7dda38cc5c2ad80c711d672cff81f82d

<script src="https://gist.github.com/yenerciftci/7dda38cc5c2ad80c711d672cff81f82d.js"></script>

**Comment by cenkce** [comment]
In this case you must just use '/pages'  path in the stackrouter and give the route, which is outside of the stackrouter, another parent path.

**Comment by cenkce** [comment]
Your paths should be like files and folders tree.

**Comment by yenerciftci** [comment]
thanks your answer. but i change both path name in router and js file path. i have got still same issue

**Comment by cenkce** [comment]
Yes this is happening because of every router has separately own history, I am checking it out.
