### ISSUE TITLE
iOS Cretes a white screen just by defining a router

### ISSUE THREAD

**Issue by alperozisik** [smartface/router#4]
**iOS**
![img_29ae8bfa52fe-1](https://user-images.githubusercontent.com/7248325/46244562-49567800-c3e9-11e8-9a84-790e2e22b200.jpeg)

**Android**
![screenshot_20180929-130217](https://user-images.githubusercontent.com/7248325/46244600-a6eac480-c3e9-11e8-8840-494c6bf482b2.png)

```javascript
const Router = require("@smartface/router/src/native/NativeRouter");
const router = Router.of({
    path: "/",
    isRoot: true,
    routes: []
});
```

This is wrong for iOS.
- Android does show the same thig if the router is not defined (ckeck #1 )
- iOS shows white screen instead of black (check #2)

**Comment by cenkce** [comment]
I'm not sure that is a bug. We talk about with core team.
