### ISSUE TITLE
BottomTabBarRouter with modal navigation weird behavior

### ISSUE THREAD

**Issue by illegalDisease** [smartface/router#41]
Router version: *any* ( tested on 1.3.5 and 1.5.1 )
workspace: ~~https://ide.r0.smartface.io/smartface32789/router-issue/~~ ( Workspace deleted )
Steps to reproduce:
- Launch the project which is present in the workspace
- Go to page4
- Click on notmodal button ( will push to a normal route )
- Click on any other BottomTabBarItem
- Come back to page4
- Get back from opened page
- Click on modal button ( will push a modal )
- Dismiss the modal by clicking the button
- Observe the behavior ( It will dismiss to a different BottomTabBarItem )
- Come back to page4 again
- Click on the modal ( more than one time )
- Observe the behavior.
- On iOS, it will be a black screen
- On Android, the navigation won't be possible anymore

Videos on both OS:
- ![routerandroid](https://user-images.githubusercontent.com/12798126/58078545-afca1980-7bb7-11e9-973f-0f15b42df174.gif)
- i![routerios](https://user-images.githubusercontent.com/12798126/58078546-b062b000-7bb7-11e9-9d87-bfce1b4879e2.gif)

Router implementation of page4:
~~~ StackRouter.of({
    path: "/btb/tab4",
    to: "/btb/tab4/page4",
    routes: [
        Route.of({
            path: "/btb/tab4/page4",
            build: buildExtender({ pageName: "page4", singleton: true, pageProps: { shouldExit: true } })
        }),
        Route.of({
            path: "/btb/tab4/notmodal",
            build: buildExtender({
                pageName: "modal",
                pageProps: { shouldExit: true }
            })
        }),
        StackRouter.of({
            path: "/btb/tab4/test",
            routes: [
                Route.of({
                    path: "/btb/tab4/test/test1",
                    build: buildExtender({
                        pageName: "modal",
                        pageProps: { shouldExit: true }
                    })
                })
            ],
            modal: true
        })
    ]
}),

**Comment by illegalDisease** [comment]
- Launch the project which is present in the workspace
- Go to page4
- Click on notmodal button ( will push to a normal route )
- Click on any other BottomTabBarItem
- Come back to page4
- Get back from opened page
- Click on modal button ( will push a modal )
- Dismiss the modal by clicking the button
- ~Observe the behavior ( It will dismiss to a different BottomTabBarItem )~ -> Fixed
- ~Come back to page4 again~ -> Fixed
- Click on the modal ( more than one time )
- Observe the behavior  -> Will not go to modal
- Click on notmodal
- Go back
- Click on modal
- Black screen
-

**Comment by cenkce** [comment]
I will be solved in new version
